default_context:
  project_name: '9x9'
  project_slug: '9x9'
  domain_main: '9x9.com'
  domain_staging: 'stag.9x9.com'
  docker_swarm_stack_name_main: '9x9-game'
  docker_swarm_stack_name_staging: 'stag-9x9-game'
  secret_key: 'bfcbc35c34610fbe9d36ca8140bb16f9a81f81776ece2f403541c31b10cbf7ea'
  first_superuser: 'admin@9x9.com'
  first_superuser_password: 'adminpassword'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://46.101.251.5, https://46.101.251.5'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@9x9.com'
  postgres_password: 'postgrespassword'
  pgadmin_default_user: 'admin@9x9.com'
  pgadmin_default_user_password: 'adminpassword'
  traefik_constraint_tag: '9x9.com'
  traefik_constraint_tag_staging: 'stag.9x9.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:adminpassword'
  sentry_dsn: ''
  docker_image_prefix: '9x9'
  docker_image_backend: '9x9backend'
  docker_image_celeryworker: '9x9celeryworker'
  docker_image_frontend: '9x9frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
